### ISSUE TITLE
use an audited HKDF for deriving the quic reset key

### ISSUE THREAD

**Issue by bmwill** [MystenLabs/anemo#12]
In order to stop using a random reset key 3bcbd2cd5c3a8b9c1c57460fe0ad879d4949dfcb used the ed25519 private key as a seed to an rng in order to generate a 64 byte long reset key. This may not be cryptographically safe and should instead be replaced with an HKDF.

https://github.com/bmwill/anemo/commit/3bcbd2cd5c3a8b9c1c57460fe0ad879d4949dfcb#r90041540
> This may not be cryptographically safe. Consider using an audited HKDF, as done e.g. in https://www.rfc-editor.org/rfc/rfc9001.html#initial-secrets.

**Comment by huitseeker** [comment]
We have [an HKDF](https://github.com/MystenLabs/fastcrypto/blob/0ab82df11360458d7539c407ad7b4581da078e2b/fastcrypto/src/hmac.rs#L115-L116) in fastcrypto!
/cc @kchalkias @joyqvq @jonas-lj

**Comment by bmwill** [comment]
Oh this was already fixed :)
