### ISSUE TITLE
Implement mock servers for unit tests

### ISSUE THREAD

**Issue by aschran** [MystenLabs/anemo#3]
There should be a conventional way to create a mock RPC server for unit testing.

**Comment by aschran** [comment]
Maybe the RPC service code generator can also generate testing impls of the service with some nice expectation/behavior-setting functions along the lines of gmock's WillOnce, WillRepeatedly, etc?

**Comment by aschran** [comment]
Maybe use mockall/automock for this?

**Comment by bmwill** [comment]
57c4af7d6cdbf47633e6715bcd67d98f300e2fd8 introduces the ability for users to specify attributes that should be applied to the generated trait. This would enable you to specify that the `automock` attribute should be added, enabling you to use the generated mocks. e.g.

```
let mut attributes = Attributes::default();
attributes.push_trait(".", r#"#[mockall::automock]"#);

let greeter_service = anemo_build::manual::Service::builder()
     .name("Greeter")
     .package("example.helloworld")
     .attributes(attributes)
```

If this isn't sufficient we can reopen this issue at a later point.
