### ISSUE TITLE
Implement native support for RPC timeouts

### ISSUE THREAD

**Issue by aschran** [MystenLabs/anemo#5]
It's possible to use tokio timeout but this leads to unwieldy types containing numerous nested `Result`s. I think default and per-RPC timeouts should be a native feature of the code generated RPC services in anemo. Timeout should be a supported error type within `anemo::rpc::Status`. Bonus if we also make client propagate its timeout to server so that the server can behave accordingly (eg fail-fast, or use it to set appropriate timeouts on Child RPCs).

**Comment by bmwill** [comment]
This doesn't even need to be implemented directly inside of anemo and could be completely handled via a tower layer

**Comment by aschran** [comment]
Maybe but I think it's worth natively supporting. It could be its own error code in anemo::rpc::Status, and propagation of timeouts as a native header. This is a pretty basic RPC framework-level feature in most systems.

**Comment by bmwill** [comment]
Closed by dd5d32549f03f51e16843ab91530727392894eb3 and 06585a7d407e029e1bb70af110b31e3db23689fd
