### ISSUE TITLE
Implement authorization support

### ISSUE THREAD

**Issue by aschran** [MystenLabs/anemo#6]
It should be possible to constrain which peers anemo will allow to connect or send certain RPCs.

**Comment by bmwill** [comment]
This is two separate problems, one could be solved in the application layer as a tower layer (restricting certain peers to being able to call particular RPCS) and the restricting who can connect to you is a bit more complicated of a problem and would require a few changes inside anemo.

**Comment by bmwill** [comment]
The ability to require authorization for requests was added in 7da7c9a1913ed7fadbdd92ebc1b9f48e0c8cef0e. If we need to have a way to restrict who can connect to us we can open up another issue later as this is a much more involved change.
